### ISSUE TITLE
Implement periodic table

### ISSUE THREAD

**Issue by M475R** [david072/funcially#10]
It would be useful for users calculating chemical formulas needing e.g. information, such as ordinal number, mass, molar mass

The elements of the periodic table can be accessed through `PT(ordinal number)` (output is the name of the element) / `PT(name of element)`  (output is ordinal number of the element) and henceforth be used by `PT(ordinal number).m` (mass) / `PT(ordinal number).Mm` (molar mass) / `PT(ordinal number).Vm`

**Comment by david072** [comment]
Thank you for submitting this feature request!

Some critic points:
- The syntax you proposed is very out of line with the rest of the features in the calculator. Perhaps making separate functions for each of the attributes would be better?
- As there don't exist strings, you'd have to pre-define a lot of "variables" for every element, potentially making it confusing since you currently also can't re-define standard variables and functions (unlikely that anyone would do this because of capitalisation but should still be considered)
- Would this only work with atoms or with every chemical class? If so, how would you write the index in e.g. molecules, since subscript numbers are not possible?

If you can, try to also provide some examples of the usage.
